exports_files(["springboot-wrapper.tmpl"])

py_binary(
    name = "springboot_jar",
    srcs = [
        "springboot_jar.py",
    ],
    main = "springboot_jar.py",
    python_version = "PY3",
    visibility = ["//visibility:public"],
    deps = [],
)
