# Copyright (c) 2017, salesforce.com, inc.
# All rights reserved.
# Licensed under the BSD 3-Clause license.
# For full license text, see LICENSE.txt file in the repo root  or https://opensource.org/licenses/BSD-3-Clause
#
# Spring Boot Packager
#
# See the macro documentation below for details.

# Spring Boot Executable JAR Layout specification
#   reverse engineered from the Spring Boot maven plugin

# /
# /META-INF/
# /META-INF/MANIFEST.MF                        <-- very specific manifest for Spring Boot (generated by this rule)
# /BOOT-INF
# /BOOT-INF/classes
# /BOOT-INF/classes/**/*.class                 <-- compiled application classes, must include @SpringBootApplication class
# /BOOT-INF/classes/META-INF/*                 <-- application level META-INF config files (e.g. spring.factories)
# /BOOT-INF/lib
# /BOOT-INF/lib/*.jar                          <-- all upstream transitive dependency jars must be here (except spring-boot-loader)
# /org/springframework/boot/loader
# /org/springframework/boot/loader/**/*.class  <-- the Spring Boot Loader classes must be here

# ***************************************************************
# SpringBoot Rule
#  do not use directly, see the SpringBoot Macro below

def _springboot_jar_rule_impl(ctx):
    # Extract the JavaInfo provider from the application Target:
    app_java_info = ctx.attr.application_lib[JavaInfo]
    runtime_jars = app_java_info.transitive_runtime_jars.to_list()

    #java_target = ctx.attr.application_lib[java_common.JavaToolchainInfo].target_version
    java_target = "OpenJDK 11"

    manifest_tmpl = """Manifest-Version: 1.0
Created-By: Bazel
Built-By: Bazel
Throw-Down: hootenanny
Main-Class: {loader_class}
Spring-Boot-Classes: BOOT-INF/classes/
Spring-Boot-Lib: BOOT-INF/lib/
Spring-Boot-Version: 2.1.5.RELEASE
Build-Jdk: {java_target}
Start-Class: {start_class}
"""

    manifest_file = ctx.actions.declare_file("%s-manifest" % ctx.label.name)
    ctx.actions.write(
        manifest_file,
        manifest_tmpl.format(
            start_class = ctx.attr.main_class,
            loader_class = ctx.attr.loader_class,
            java_target = java_target,
        ),
    )

    loader_runtime_jars = ctx.attr.loader[JavaInfo].transitive_runtime_jars.to_list()

    helper_args = ctx.actions.args()
    helper_args.add_all(runtime_jars, before_each = "--runtime_jars")
    helper_args.add_all(loader_runtime_jars, before_each = "--loader_jars")
    helper_args.add_all(["--application_jar", ctx.file.application_lib])
    helper_args.add_all(["--boot_manifest", manifest_file])
    helper_args.add_all(["--zip_exe", ctx.executable._zip])
    helper_args.add_all(["--unzip_exe", ctx.executable._unzip])
    helper_args.add_all(["--output_jar", ctx.outputs.bootjar])
    helper_args.add_all(["--stable_status", ctx.info_file])
    helper_args.add_all(["--volatile_status", ctx.version_file])

    ctx.actions.run(
        executable = ctx.executable._py_helper,
        arguments = [helper_args],
        outputs = [ctx.outputs.bootjar],
        tools = [
            ctx.executable._zip,
            ctx.executable._unzip,
        ],
        progress_message = "Constructing boot jar %s" % ctx.label.name,
        inputs = [
            manifest_file,
            ctx.file.loader,
            ctx.info_file,
            ctx.version_file,
            ctx.file.application_lib,
        ] + runtime_jars + loader_runtime_jars,
    )
    
    java_exec = None
    for jdk_file in ctx.files._jdk:
      if jdk_file.short_path.endswith("/java"):
        java_exec = jdk_file

    java_exec_path = java_exec.path
    if java_exec_path.startswith("external/"):
      java_exec_path = java_exec_path.replace("external/", "")

    wrapper_file = ctx.actions.declare_file("%s-wrapper" % ctx.label.name)
    ctx.actions.expand_template(
        template=ctx.file._wrapper_tmpl,
        output=wrapper_file,
        is_executable = True,
        substitutions = {
            "%javabin%": java_exec_path,
            "%springboot_jar%": ctx.outputs.bootjar.short_path,
        })
    transitive_deps = depset(direct=ctx.files._jdk)
    exec_runfiles = ctx.runfiles(files=[ctx.outputs.bootjar, wrapper_file], transitive_files=transitive_deps)

    return [DefaultInfo(executable = wrapper_file, default_runfiles=exec_runfiles)]

springboot_jar = rule(
    implementation = _springboot_jar_rule_impl,
    executable = True,
    attrs = {
        "main_class": attr.string(),
        "application_lib": attr.label(
            allow_single_file = True,
        ),
        "loader": attr.label(
            default = Label("//third_party:org_springframework_boot_loader"),
            allow_single_file = True,
        ),
        "loader_class": attr.string(
            default = "org.springframework.boot.loader.JarLauncher",
        ),
        "_py_helper": attr.label(
            executable = True,
            cfg = "host",
            default = Label("//tools/bzl:springboot_jar"),
            allow_files = True,
        ),
        "_unzip": attr.label(
            executable = True,
            cfg = "host",
            default = Label("//third_party/infozip:unzip"),
            allow_files = True,
        ),
        "_zip": attr.label(
            executable = True,
            cfg = "host",
            default = Label("//third_party/infozip:zip"),
            allow_files = True,
        ),
        "_jdk": attr.label(
            default = Label("@bazel_tools//tools/jdk:current_java_runtime"),
            providers = [java_common.JavaRuntimeInfo],
        ),
        "_wrapper_tmpl": attr.label(
            default = Label("//tools/bzl:springboot-wrapper.tmpl"),
            allow_single_file = True,
        ),
    },
    outputs = {
        "bootjar": "%{name}.jar",
    },
)
